Add Linux support.
lesnitsky/native_context_menu pull request #7
Opened 2021-09-28 14:32 UTC by alexmercerind

**This PR adds:**
- Linux support.

NOTE: I made native code itself find the menu coordinates and show the menu accordingly.

I noticed that you are passing the context menu coordinates from Dart (which is perfectly fine), so I declared an optional macro `USE_FLUTTER_POSITION` to use those coordinates on Linux instead of using GTK's method (to use it just add `#define USE_FLUTTER_POSITION` at the start of the file). I do not recommend this however since it was causing problems for me on the Wayland. 

I believe code is nicely arranged & I have added good amount of comments explaining everything.

https://user-images.githubusercontent.com/28951144/135107609-8f02281a-3492-4f22-a09a-7425d4980dee.mp4

I will be happy if I get credited or something. 😄

2021-09-28 14:39 UTC, alexmercerind commented
Another thing that I should mention is that, I had to add event handler on Dart because everything in GTK is callback based and follows very standard GObject style. It doesn't even support capturing lambdas. Thus, a `Completer` is used to wait for the selected menu item's id or menu dismiss event.

I see Windows code is also dealing with this problem by `std::move`-ing the result, which isn't the best way to do it, thus involved a lot of unnecessary code.

Let me know if you want any changes in the code or feel free to make edits yourself. For the functionality part, I believe its working great.

Thankyou.

2021-09-28 15:06 UTC, lesnitsky commented
I'd appreciate if you can migrate windows code to event handler as well. I'll.handle macos on my own

Great work 👍 Appreciate it

2021-09-28 19:27 UTC, alexmercerind commented
@lesnitsky I've refactored Windows aswell & follows [Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html).

Now Windows doesn't require `devicePixelRatio` or `position` either. Feel free to remove them if macOS doesn't need it. 

Same macro `USE_FLUTTER_POSITION` is added (like Linux) if you wish to use the passed positioning instead of the cursor's position. Maybe in future, plugin would wanna support opening context menu at any location & not just by right click.

2021-09-28 19:30 UTC, alexmercerind commented on lib/src/method_channel.dart
> +  _completer = Completer<int>();
Just for the note, now macOS implementation needs to be updated accordingly.

2021-09-29 17:43 UTC, lesnitsky requested changes
being able to show the context menu programmatically is a nice feature to have. Instead of `USE_FLUTTER_POSITION` define, I'd go with the approach where position argument becomes optional and native uses the position from flutter if it was passed – otherwise uses the one from native

2021-09-29 17:43 UTC, lesnitsky commented on lib/src/context_menu_region.dart
> +        }
are you on the latest master? this was dropped

2021-09-29 17:43 UTC, lesnitsky commented on lib/src/method_channel.dart
> +import 'dart:io';
unused import

2021-09-29 17:43 UTC, lesnitsky commented on lib/src/method_channel.dart
> +            // Notify about the selected menu item's id & complete the future.
the comment is redundant, code is pretty much self-explanatory

2021-09-29 17:43 UTC, lesnitsky commented on lib/src/method_channel.dart
> +        case 'id':
rename to `onItemSelected`
also it makes sense to add another method `onMenuDismissed` instead of sending `-1`

2021-09-29 17:43 UTC, lesnitsky commented on lib/src/method_channel.dart
> +          break;
should throw an exception

2021-09-29 17:43 UTC, lesnitsky commented on lib/src/method_channel.dart
> +  _channel.invokeMethod('showMenu', args.toJson());
why drop newlines? 🙂

2021-09-29 17:43 UTC, lesnitsky commented on lib/src/method_channel.dart
> +  int id = await _completer.future;
revert back to `final`

2021-09-29 17:43 UTC, lesnitsky commented on lib/src/method_channel.dart
> -
newlines is a matter of preference, don't drop these just because you personally don't like them 🙂

2021-10-01 08:20 UTC, alexmercerind commented
@lesnitsky I have raised #8 with your proposed changes & the code for being able to show the context menu programmatically. 

May you review & merge.

Thankyou.

2021-10-01 08:20 UTC, closed without merging